// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzlTk3LCP97b15xz_Z1FLK2pC7NoL3i6w',
    appId: '1:236584419816:web:7531810632b0a45a53245d',
    messagingSenderId: '236584419816',
    projectId: 'smartbin-96489',
    authDomain: 'smartbin-96489.firebaseapp.com',
    databaseURL: 'https://smartbin-96489-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-96489.appspot.com',
    measurementId: 'G-QT3F7H91T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGKX6hC5v6jaGjDHsx2LY0554Nd3FKI7k',
    appId: '1:236584419816:android:9498d48a11dea7e553245d',
    messagingSenderId: '236584419816',
    projectId: 'smartbin-96489',
    databaseURL: 'https://smartbin-96489-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-96489.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnCC0jvgrzTQhd45htFgIWy1iOdpYt-oM',
    appId: '1:236584419816:ios:7d2f92bb19ed6c4253245d',
    messagingSenderId: '236584419816',
    projectId: 'smartbin-96489',
    databaseURL: 'https://smartbin-96489-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-96489.appspot.com',
    iosBundleId: 'com.example.wastemanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnCC0jvgrzTQhd45htFgIWy1iOdpYt-oM',
    appId: '1:236584419816:ios:4098f40d48b3419453245d',
    messagingSenderId: '236584419816',
    projectId: 'smartbin-96489',
    databaseURL: 'https://smartbin-96489-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbin-96489.appspot.com',
    iosBundleId: 'com.example.wastemanagement.RunnerTests',
  );
}
